// =============================================================================
// tb_afpos_multiplier.v  —  AxLAM Testbench
// Unit testbench for afpos_multiplier.v
//
// Reads test vectors from sim/vectors/afpos_mul_tests.hex (generated by
// sim/gen_test_vectors.py) and checks bit-exact match against Python golden.
//
// Hex file format (one test per line):
//   <a_hex> <b_hex> <expected_p_hex>
//   e.g.: 4F 3A 89
// =============================================================================
`timescale 1ns/1ps

module tb_afpos_multiplier;

    reg  [7:0] a, b;
    wire [7:0] p;

    // DUT
    afpos_multiplier dut (.a(a), .b(b), .p(p));

    integer pass_cnt = 0;
    integer fail_cnt = 0;
    integer vec_fd;
    integer scan_ret;
    reg [7:0] exp_p;
    integer a_int, b_int, exp_int;
    integer test_num;

    initial begin
        $dumpfile("sim/waves/tb_afpos_mul.vcd");
        $dumpvars(0, tb_afpos_multiplier);

        // ----------------------------------------------------------------
        // Inline corner-case tests (zero, max, sign)
        // ----------------------------------------------------------------
        test_num = 0;

        // Test 0: 0 * anything = 0
        a = 8'h00; b = 8'h4F; #10;
        check(a, b, p, 8'h00, test_num); test_num = test_num + 1;

        // Test 1: anything * 0 = 0
        a = 8'h4F; b = 8'h00; #10;
        check(a, b, p, 8'h00, test_num); test_num = test_num + 1;

        // Test 2: 1.0 * 1.0 = 1.0
        // 1.0 = sign=0, exp=7, mant=0 → 8'b0_0111_000 = 8'h38
        a = 8'h38; b = 8'h38; #10;
        check(a, b, p, 8'h38, test_num); test_num = test_num + 1;

        // Test 3: -1.0 * 1.0 = -1.0
        // -1.0 = 8'b1_0111_000 = 8'hB8
        a = 8'hB8; b = 8'h38; #10;
        check(a, b, p, 8'hB8, test_num); test_num = test_num + 1;

        // Test 4: -1.0 * -1.0 = +1.0
        a = 8'hB8; b = 8'hB8; #10;
        check(a, b, p, 8'h38, test_num); test_num = test_num + 1;

        // Test 5: 2.0 * 2.0 = 4.0
        // 2.0 = sign=0, exp=8, mant=0 → 8'b0_1000_000 = 8'h40
        // 4.0 = sign=0, exp=9, mant=0 → 8'b0_1001_000 = 8'h48
        a = 8'h40; b = 8'h40; #10;
        check(a, b, p, 8'h48, test_num); test_num = test_num + 1;

        // Test 6: Max * Max → saturate
        // max = sign=0, exp=F, mant=7 → 8'b0_1111_111 = 8'h7F
        a = 8'h7F; b = 8'h7F; #10;
        check(a, b, p, 8'h7F, test_num); test_num = test_num + 1;

        // ----------------------------------------------------------------
        // File-based tests (Python generated)
        // ----------------------------------------------------------------
        vec_fd = $fopen("sim/vectors/afpos_mul_tests.hex", "r");
        if (vec_fd == 0) begin
            $display("NOTE: sim/vectors/afpos_mul_tests.hex not found, skipping file tests.");
            $display("      Run sim/gen_test_vectors.py first to generate vectors.");
        end else begin
            scan_ret = $fscanf(vec_fd, "%h %h %h\n", a_int, b_int, exp_int);
            while (scan_ret == 3) begin
                a = a_int[7:0];
                b = b_int[7:0];
                exp_p = exp_int[7:0];
                #10;
                check(a, b, p, exp_p, test_num);
                test_num = test_num + 1;
                scan_ret = $fscanf(vec_fd, "%h %h %h\n", a_int, b_int, exp_int);
            end
            $fclose(vec_fd);
        end

        // ----------------------------------------------------------------
        // Summary
        // ----------------------------------------------------------------
        $display("===================================");
        $display("AFPOS Multiplier Test Summary");
        $display("  Total tests : %0d", test_num);
        $display("  PASS        : %0d", pass_cnt);
        $display("  FAIL        : %0d", fail_cnt);
        $display("===================================");
        if (fail_cnt == 0)
            $display("ALL TESTS PASSED");
        else
            $display("*** FAILURES DETECTED ***");
        $finish;
    end

    // -----------------------------------------------------------------------
    // Check task
    // -----------------------------------------------------------------------
    task check;
        input [7:0] in_a, in_b, got, expected;
        input integer t;
        begin
            if (got === expected) begin
                pass_cnt = pass_cnt + 1;
            end else begin
                fail_cnt = fail_cnt + 1;
                $display("FAIL [test %0d]: a=0x%02h b=0x%02h  got=0x%02h  expected=0x%02h",
                         t, in_a, in_b, got, expected);
            end
        end
    endtask

endmodule
